# Dependencies
markdown:            redcarpet
highlighter:         pygments

# Permalinks
#
# Use of `relative_permalinks` ensures post links from the index work properly.
permalink:           pretty
relative_permalinks: true

# Setup
title:               retrography
tagline:             'backwardly writing...'
description:         "I am Mahmood Zargar, a PhD candidate in McGill's Desautels Faculty of Management. I am passionate about social theory and have a knack for data wrangling. My research is about the organizational aspects of online communities. Here are some related posts. Btw, call me Mah."
url:                 'http://retrography.github.io'
baseurl:             ''
paginate:            5

# About/contact
author:
  name:              Mahmood S. Zargar
  url:               https://twitter.com/mszargar
  email:             mahmood@gmail.com

# Custom vars
version:             1.0.0
