# Dependencies
markdown:            redcarpet
highlighter:         pygments

# Permalinks
#
# Use of `relative_permalinks` ensures post links from the index work properly.
permalink:           pretty
relative_permalinks: true

# Setup
title:               retrography
tagline:             'backwardly writing...'
description:         "I am a PhD candidate in management at McGill. I like data and social theory. Here are some related posts. Btw, call me mah."
url:                 'http://retrography.github.io/'
baseurl:             ''
paginate:            5

# About/contact
author:
  name:              Mahmood Zargar
  url:               https://twitter.com/mszargar
  email:             mahmood@gmail.com

# Custom vars
version:             1.0.0
