markdown: redcarpet
highlighter: null
permalink: /:title

url: http://retrography.github.io
baseurl: http://retrography.github.io

redcarpet:
  extensions: [strikethrough, tables]

sass:
  sass_dir: public/css
  style: :compressed