# Dependencies
markdown:            redcarpet
highlighter:         pygments

# Permalinks
#
# Use of `relative_permalinks` ensures post links from the index work properly.
permalink:           pretty
relative_permalinks: true

# Setup
title:               retrography
tagline:             'backwardly writing...'
description:         "Call me Mah. I'm a PhD candidate in management at McGill University. I like data and social theory and here are some related posts. I currently teach a course called <a href='http://retrography.github.io/data-management/'>Managing Data and Databases</a>."
url:                 http://retrography.github.io
baseurl:             ''
paginate:            5

# About/contact
author:
  name:              Mahmood Zargar
  url:               https://twitter.com/mszargar
  email:             mahmood@gmail.com

# Custom vars
version:             1.0.0
