# Dependencies
markdown:            redcarpet
highlighter:         pygments

# Permalinks
#
# Use of `relative_permalinks` ensures post links from the index work properly.
permalink:           pretty
relative_permalinks: true

# Setup
title:               retrography
tagline:             'backwardly writing...'
description:         "I am a PhD candidate in McGill's Desautels Faculty of Management. Passionate about social theory and having a knack for data wrangling, I study the organizational aspects of online communities. Here are some related posts."
url:                 'http://retrography.github.io'
baseurl:             ''
paginate:            5

# About/contact
author:
  name:              Mahmood S. Zargar
  url:               https://twitter.com/mszargar
  email:             mahmood@gmail.com

# Custom vars
version:             1.0.0
